name = "backend"
main = "src/index.ts"
compatibility_date = "2024-10-29"
compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiODFiZGYyNjgtMTMyMi00NDhkLWI0MWMtNzc4NWQzOTk2ZTM4IiwidGVuYW50X2lkIjoiZDEwMmQwZmI2NWU2ZjdlMGQ2OWZiMzg1NzY0MTlhMjgxYTM1NWUyYWY2NWY2NDk5Zjc5OGUxZjNiNzdkMGRhYiIsImludGVybmFsX3NlY3JldCI6IjIxZjIxNzFmLWIzMjYtNGIxMi04ZDNkLWY5MTdkYzQ5ZjE1OSJ9.p02OuTLV5ShsRl20U0MBBXd32qWia2IROT9eTCkEbhc"
JWT_SECRET="monkey-d-luffy"

